# Sponsor links shown on the repository's "Sponsor" button.
# Uncomment each line once the account exists. Open Source Collective (Open Collective's
# main fiscal host) only accepts OSI-licensed projects, so it is not listed here.
# github: [your-github-username]
# patreon: your-patreon-name
# custom: ["https://tumblbug.com/your-project", "https://dotori.ai/support"]
